name: Run TS script
description: Run a TypeScript script

inputs:
  github-token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  script:
    description: The script to run
    required: false
  script-filename:
    description: Path to the script to run
    required: false

outputs:
  result:
    description: Raw JSON output of the script step if any
    value: ${{ toJSON(steps.script.outputs) }}

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - shell: bash
      run: npm install --global esbuild

    - id: env
      shell: bash
      run: echo "node-path=$(npm list --global | head -1)/node_modules" >> $GITHUB_OUTPUT

    - id: script
      shell: bash
      env:
        NODE_PATH: ${{ steps.env.outputs.node-path }}
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_SCRIPT: ${{ inputs.script }}
        INPUT_SCRIPT-FILENAME: ${{ inputs.script-filename }}
      run: node ${{ github.action_path }}/index.js
