name: Send a deployment notification via Discord
description: Send a deployment notification via Discord

inputs:
  webhook-url:
    description: Webhook url
    required: true
  status:
    description: Status of the job, one of success, failure, or pending
    required: true
  payload-format:
    description: Format of the webhook payload, one of slack, discord, or raw
    required: false

runs:
  using: node20
  main: index.js
