name: Send a deployment notification via Discord
description: Send a deployment notification via Discord

inputs:
  webhook-url:
    description: Discord webhook url
    required: true

  status:
    description: One of "pending", "success", or "failed"
    required: false
    default: "pending"

runs:
  using: composite

  steps:
    - uses: actions/setup-python@v4
      with:
        version: 3.11

    - shell: bash
      run: pip install requests

    - shell: python
      run: |
        import os
        from urllib import request

        # inputs
        webhook_url = "${{ inputs.webhook-url }}"
        status = "${{ inputs.status }}"

        # github context
        job_status = "${{ job.status }}"
        run_id = "${{ github.run_id }}"
        repository_url = "${{ github.event.repository.html_url }}"

        titles = {
          "pending": "Deployment pending review",
          "success": "Deployment complete",
          "failure": "Deployment failed",
        }

        title = titles.get(status, titles["pending"])

        colors = {
          "pending": 16170496,
          "success": 65280,
          "failure": 16711680,
        }

        color = colors.get(status, colors["pending"])

        request.urlopen(webhook_url, data={
          "embeds": [{
            "title": title,
            "type": "rich",
            "color": color,
            "description": "\n".join([
              f"Run conclusion: {job_status}",
              f"- [Workflow run]({repository_url}/actions/runs/{run_id})",
              f"- [Repository]({repository_url})",
              f"- [Deployment history]({repository_url}/deployments/activity_log)",
            ]),
          }],
        })
