name: Send a deployment notification via Discord
description: Send a deployment notification via Discord

inputs:
  webhook-url:
    description: Discord webhook url
    required: true

  status:
    description: One of "pending", "success", or "failed"
    required: false
    default: "pending"

runs:
  using: composite

  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - shell: bash
      run: pip install requests

    - shell: bash
      run: python "${{ github.action_path }}/script.py"
