name: Assume AWS Role
description: Wrapper for aws-actions/configure-aws-credentials

inputs:
  aws-region:
    description: AWS Region
    required: false
    default: ap-southeast-2

  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the 
      Actions environment with the assumed role credentials rather than with
      the provided credentials
    required: true

runs:
  using: composite

  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ github.triggering_actor }}@${{ github.event.repository.owner.login }}@${{ github.event.repository.name }}@${{ github.job }}@${{ github.run_id }}
        role-skip-session-tagging: true
        role-duration-seconds: 3600
        mask-aws-account-id: true
        disable-retry: true
