name: Get AWS SSM parameter
description: Get and obscures an AWS SSM parameter

inputs:
  path:
    description: Parameter path

  env-name:
    description: Name of environment variable to export the value
    required: false
    default: ""

outputs:
  value:
    description: Parameter value
    value: ${{ steps.value.output.value }}

runs:
  using: composite
  steps:
    - id: value
      shell: bash
      run: |
        value=$(
          aws ssm get-parameter \
            --name "${{ inputs.path }}" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text
        )

        echo "::add-mask::${value}"
        echo "value=${value}" >> $GITHUB_OUTPUT

        if [[ "${{ inputs.env-name }}" != "" ]]; then
          echo "${{ inputs.env-name }}=${{ steps.value.output.value }}" >> $GITHUB_ENV
        fi
