name: Prune ECR Repository
description: Prune ECR Repository
inputs:
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  repository-name:
    description: Target repository to prune
    required: true

runs:
  using: node16
  main: index.js
