name: Search entity GUID
description: Searches for the GUID of an entity in New Relic

inputs:
  name:
    description: Entity name
    required: true

  api-key:
    description: New Relic API key
    required: true

  domain:
    description: Entity domain
    required: false
    default: APM

  type:
    description: Entity type
    required: false
    default: APPLICATION

runs:
  using: node20
  main: index.js
