on:
  workflow_call:

jobs:
  test-no-use-cache:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: ./docker-build-push
        with:
          image: axatol/test
          build-args: -f ./docker-build-push/Dockerfile.test
          use-cache: false
          dry-run: true

  test-no-tag-previous:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: ./docker-build-push
        with:
          image: axatol/test
          build-args: -f ./docker-build-push/Dockerfile.test
          tag-previous: false
          dry-run: true
