name: Test

on:
  pull_request:
  workflow_call:

jobs:
  test-run-ts-script:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - run: |
          npm --workspace=run-ts-script install
          npm --workspace=run-ts-script run compile

      - name: Test inline JavaScript-compatible script
        uses: ./run-ts-script
        with:
          script: console.log({ core, exec, github, io });

      - name: Test inline TypeScript script
        uses: ./run-ts-script
        with:
          script: |
            interface Test {
              foo: string;
              bar: number;
            }

            const fn = (test: Test): Test => {
              console.log(test);
              return test;
            };

            fn({ foo: "foo", bar: 1 });

      - run: |
          cat <<EOF > test.ts
          type Blah = { bleh: string };
          const blah: Blah = { bleh: "bleh" };
          EOF

      - name: Test running TypeScript script file
        uses: ./run-ts-script
        with:
          script-filename: test.ts

  test-docker-build-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: ./docker-build-push
        with:
          image: axatol/docker-build-push-test-image
          next-tag: next
          previous-tag: previous
          tag-previous: true
          use-cache: true
          build-context: ./docker-build-push
          build-args: --file ./docker-build-push/Dockerfile.test
          dry-run: true

  test-watch-octopus-deploy-task:
    runs-on: self-hosted

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: OctopusDeploy/login@v1
        with:
          server: http://octopus-deploy.octopus.svc.cluster.local
          service_account_id: 74f688d0-6e11-4ed2-a438-ad1fca0ef1d5

      - id: release
        uses: OctopusDeploy/create-release-action@v3
        with:
          space: Default
          project: Test Project

      - id: deploy
        uses: OctopusDeploy/deploy-release-action@v3
        with:
          space: Default
          project: Test Project
          environments: Development
          release_number: ${{ steps.release.outputs.release_number }}

      - run: echo "$TASK_IDS"
        env:
          TASK_IDS: ${{ steps.deploy.outputs.server_tasks }}

      - uses: ./watch-octopus-deploy-task
        with:
          SERVER_URL: https://octopus.k8s.axatol.xyz
          API_KEY: ${{ secrets.OCTOPUS_DEPLOY_API_KEY }}
          TASK_IDS: ${{ join(fromJson(steps.deploy.outputs.server_tasks.*.serverTaskId)) }}
