name: Test

on:
  pull_request:
  workflow_call:

jobs:
  test-run-ts-script:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: ./run-ts-script
        with:
          script: console.log({ core, exec, github, io });

      - uses: ./run-ts-script
        with:
          script: |
            interface Test {
              foo: string;
              bar: number;
            }

            const fn = (test: Test): Test => {
              console.log(test);
              return test;
            };

            fn({ foo: "foo", bar: 1 });

      - run: |
          cat <<EOF > test.ts
          type Blah = { bleh: string };
          const blah: Blah = { bleh: "bleh" };
          EOF

      - uses: ./run-ts-script
        with:
          script-filename: test.ts

  test-docker-build-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: ./docker-build-push
        with:
          next-tag: next
          previous-tag: previous
          tag-previous: true
          use-cache: true
          build-context: ./docker-build-push
          build-args: --file Dockerfile.test
          dry-run: true
