name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "actions-runner/**"
      - "**/README.md"

jobs:
  test:
    uses: ./.github/workflows/_test.yaml

  release:
    needs:
      - test

    runs-on:
      - self-hosted

    concurrency:
      group: release

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"

      - name: Sync changes from master
        run: |
          git merge --strategy-option theirs --no-ff origin/master

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Compile actions
        run: npm run compile

      - name: Stage release assets
        run: |
          workspaces=$( jq --raw-output --monochrome-output '.workspaces[]' ./package.json )
          for workspace in $workspaces; do git add --force "$workspace/index.js"; done

      - name: Release assets
        run: |
          git commit --allow-empty --message "Release: $( date +"%Y-%m-%d-%H%M" )"
          git push origin release
          git rev-parse HEAD
