name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on:
      - self-hosted

    concurrency:
      group: release

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release

      - name: Sync changes from main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Compile actions
        run: yarn compile

      - name: Release assets
        run: |
          git commit -am "Release: $( date +\"%Y-%m-%d-%H%M\" )"
          git push origin release
