name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on:
      - self-hosted

    concurrency:
      group: release

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release

      - name: Configure git identity
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"

      - name: Sync changes from main
        run: |
          git fetch origin main
          git merge -X theirs --no-ff --allow-unrelated-histories origin/main

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Compile actions
        run: npm run compile

      - name: Stage release assets
        run: |
          workspaces=$( jq -rM '.workspaces[]' ./package.json )
          for workspace in $workspaces; do
            git add -f "$workspace/*.js"
          done

      - name: Release assets
        run: |
          git commit -am "Release: $( date +\"%Y-%m-%d-%H%M\" )"
          git push origin release
